### ISSUE TITLE
Replace dead link

### ISSUE THREAD

**Issue by mischah** [micromata/awesome-javascript-learning#30]
The following link in the section **Single Topics** is dead 😕

- [Array operations](https://danmartensen.svbtle.com/javascripts-map-reduce-and-filter) - Covering the usefulness of Array’s map, reduce, and filter methods.

Do anyone have a good alternative describing map/reduce/filter in a really awesome way?

Please leave comments in this issue before creating a PR.

**Comment by Haroenv** [comment]
https://www.robinwieruch.de/javascript-fundamentals-react-requirements/#react-javascript-map-reduce-filter

**Comment by mischah** [comment]
Thanks. But I would prefer an article not specific to React.

**Comment by Haroenv** [comment]
That specific point isn't related to react, but I get what you mean

**Comment by mischah** [comment]
The original link is up again 😅
