### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by Ahmed-ui945** [micromata/awesome-javascript-learning#71]

**Comment by mischah** [comment]
🤔

**Comment by Mandeep0001** [comment]
???

**Comment by mischah** [comment]
![?](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdXJqczB3bDB3NjEzNWpwaHM4bzBnNWVubTQwcnpveTNyMm41bWloYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l3q2K5jinAlChoCLS/giphy.gif)
