### ISSUE TITLE
JavaScript References – ECMAScript

### ISSUE THREAD

**Issue by schnittstabil** [micromata/awesome-javascript-learning#9]
Well it's just missing – I would fully understand if you believe it is too advanced for the audience this list targets.

> ## JavaScript References
> - [ECMAScript® Language Specification](http://ecma-international.org/publications/standards/Ecma-262.htm) - The standard JavaScript is based on. Only for very advanced learners.

**Comment by mischah** [comment]
A PR is welcome :octocat:
